# fly.toml app configuration file generated for simple-invoicer on 2024-08-27T14:43:14+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'simple-invoicer'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
